WebApplication1/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class AboutModel : PageModel
    {
        public string MdText { get; set; }
        
        public IActionResult OnPost(Dto dto)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            MdText = dto.MdText;

            return Page();
        }
    }

    public class Dto
    {
        public string MdText { get; set; }
    }
}

WebApplication1/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class ContactModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string Title { get; set; }

        public void OnGet()
        {
        }
    }
}

WebApplication1/Pages/Edit.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class EditModel : PageModel
    {
        public EditModel()
        {
        }
        
        public IActionResult OnGet()
        {
            return Page();
        }
        
        public IActionResult OnPost(List<IFormFile> image, string alt)
        {
            var r = new
            {
                data = new
                {
                    link = "https://i.imgur.com/89lzkTD.png"
                },
                success = true
            };
            
            // {
            //     "data":{"id":"89lzkTD","title":null,"description":null,"datetime":1538831904,"type":"image\/png","animated":false,"width":960,"height":403,"size":56162,"views":0,"bandwidth":0,"vote":null,"favorite":false,"nsfw":null,"section":null,
            //         "account_url":null,"account_id":0,"is_ad":false,"in_most_viral":false,"has_sound":false,"tags":[],"ad_type":0,"ad_url":"","in_gallery":false,"deletehash":"IgE4IqzQIAHsXxu","name":"",
            //         "link":"https:\/\/i.imgur.com\/89lzkTD.png"},
            //     "success":true,
            //     "status":200
            // } 
            return new OkObjectResult(r);
        }
    }
}

WebApplication1/Pages/Edit2.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class Edit2Model : PageModel
    {
        public Edit2Model()
        {
        }

        public IActionResult OnGet()
        {
            if (TempData.ContainsKey("H"))
            {
               Html = TempData["H"].ToString();
            }
            if (TempData.ContainsKey("M"))
            {
               Md = TempData["M"].ToString();
            }
            return Page();
        }
        
        [BindProperty(Name = "editormd-image-file")]
        public IFormFile File { get; set; }
        
        [BindProperty(Name = "test-editormd-html-code")]
        public string Html { get; set; }
        
        [BindProperty(Name = "test-editormd-markdown-doc")]
        public string Md { get; set; }
        
        public IActionResult OnPostImg(long guid)
        {
            return new OkObjectResult(new
            {
                success = 1, // 0 表示上传失败，1 表示上传成功
                message = "Success",
                url = "https://i.imgur.com/89lzkTD.png" // 上传成功时才返回
            });
        }
        
        public IActionResult OnPost()
        {
            TempData["H"] = Html;
            TempData["M"] = Md;
            return RedirectToPage();
        }
    }
}

WebApplication1/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication1/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Firebase.Storage;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Firebase.Auth;
using Firebase.Database;
using Firebase.Database.Query;

namespace WebApplication1.Pages
{
    public class IndexModel : PageModel
    {
        public IndexModel()
        {
            ImgUrl = new List<string>();
        }

        public List<string> ImgUrl { get; set; }
        public Data FObject { get; set; }
        public string Key { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            var auth = new FirebaseAuthProvider(new FirebaseConfig(""));
            var a = await auth.SignInWithEmailAndPasswordAsync("cash@cashwu.com", "");
            
            var firebaseClient = new FirebaseClient("https://.firebaseio.com/", new FirebaseOptions
            {
                AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken)
            });
            
            var data = await firebaseClient.Child("data")
                                           .OrderByKey()
                                           .LimitToFirst(1)
                                           .OnceAsync<Data>();
            
            FObject = data.FirstOrDefault()?.Object;
            Key = data.FirstOrDefault()?.Key;

            return Page();
        }

        public async Task<IActionResult> OnPostDataAsync()
        {
            var auth = new FirebaseAuthProvider(new FirebaseConfig(""));
            var a = await auth.SignInWithEmailAndPasswordAsync("cash@cashwu.com", "");

            var firebaseClient = new FirebaseClient("https://.firebaseio.com/", new FirebaseOptions
            {
                AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken)
            });

            var obj = await firebaseClient.Child("data")
                                          .PostAsync(new Data
                                          {
                                              Name = "T",
                                              Url = "url"
                                          });
            FObject = obj.Object;
            Key = obj.Key;

            return Page();
        }

        public async Task<IActionResult> OnPostDataUpdateAsync()
        {
            Key = "-LNNfUTWxJF-Iuq8_Iqv";

            var auth = new FirebaseAuthProvider(new FirebaseConfig(""));
            var a = await auth.SignInWithEmailAndPasswordAsync("cash@cashwu.com", "");

            var firebaseClient = new FirebaseClient("https://.firebaseio.com/", new FirebaseOptions
            {
                AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken)
            });

            await firebaseClient.Child("data")
                                .Child(Key)
                                .PutAsync(new
                                {
                                    Name = "T3",
                                    Url = "url3"
                                });

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(List<IFormFile> files)
        {
            if (files.Count == 0)
            {
                return Page();
            }

            foreach (var file in files)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    ms.Seek(0, SeekOrigin.Begin);

                    var auth = new FirebaseAuthProvider(new FirebaseConfig(""));
                    var a = await auth.SignInWithEmailAndPasswordAsync("cash@cashwu.com", "");
                    var url = await new FirebaseStorage(".appspot.com", new FirebaseStorageOptions
                                    {
                                        AuthTokenAsyncFactory = () => Task.FromResult(a.FirebaseToken),
                                        ThrowOnCancel = true
                                    })
                                    .Child("data")
                                    .Child(file.FileName)
                                    .PutAsync(ms);

                    ImgUrl.Add(url);
                }
            }

            return Page();
        }
    }

    public class Data
    {
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

WebApplication1/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication1/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}

<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css">
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.3/dist/css/themes/beagle.min.css" integrity="sha256-k5u1uYe3RZT8MnP+a48Wl72CmkY+IgwCFQ2gD5d3Y28=" crossorigin="anonymous">

<form method="post" style="margin-top: 100px;" id="form">
    <div class="form-group">
        <div class="col-md-10">
            <textarea id="editable" class="editable medium-editor-textarea"></textarea>
            <input type="hidden" id="hid" name="mdtext"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="button" value="submit" id="btnSubmit"/>
        </div>
    </div>
</form>

<br/>
<hr/>

@Html.Raw(Model.MdText)

@section Scripts
{
    <script src="//code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>

    <script>

        var editor = new MediumEditor('#editable',
            {
                autoLink: true,
                buttonLabels: 'fontawesome',
                toolbar: {
                    buttons: [
                        'bold', 'italic', 'underline', 'strikethrough', 'quote', 'anchor', 'justifyLeft',
                        'justifyCenter', 'justifyRight', 'justifyFull', 'superscript', 'subscript', 'orderedlist',
                        'unorderedlist', 'pre', 'outdent', 'indent', 'h1', 'h2', 'h3'
                    ],
                    static: true,
                    sticky: true
                },
                paste: {
                    cleanPastedHTML: true,
                    cleanAttrs: ['style', 'dir'],
                    cleanTags: ['label', 'meta'],
                    unwrapTags: ['sub', 'sup']
                }
            });

        $("#btnSubmit").click(function() {
            var val = editor.getContent();
            console.log(val);
            $("#hid").val(val);
            $("#form").submit();
        });

    </script>
}

WebApplication1/Pages/Contact.cshtml
@page 
@model ContactModel

@{
    ViewData["Title"] = "Contact";
}


<h1>@Model.Title</h1>

WebApplication1/Pages/Edit.cshtml
@page
@model EditModel

@{
}

<link rel="stylesheet" href="~/dist/ui/trumbowyg.min.css"/>
<link rel="stylesheet" href="~/dist/plugins/highlight/ui/trumbowyg.highlight.min.css"/>
<link rel="stylesheet" href="~/lib/prism.css"/>
<link rel="stylesheet" href="~/dist/plugins/colors/ui/trumbowyg.colors.min.css"/>
<link rel="stylesheet" href="~/dist/plugins/table/ui/trumbowyg.table.min.css"/>
<h2>Edit</h2>

// https://alex-d.github.io/Trumbowyg/demos/#plugins-history

<textarea id="edit"></textarea>

@section Scripts
{
    <script src="//cdn.rawgit.com/Alex-D/Trumbowyg/v2.10.0/dist/trumbowyg.js"></script>
    @* <script src="~/dist/trumbowyg.js"></script> *@
    <script src="~/dist/langs/zh_tw.min.js"></script>
    <script src="~/dist/plugins/cleanpaste/trumbowyg.cleanpaste.min.js"></script>
    <script src="~/dist/plugins/pasteimage/trumbowyg.pasteimage.min.js"></script>
    <script src="~/dist/plugins/base64/trumbowyg.base64.min.js"></script>
    <script src="~/dist/plugins/upload/trumbowyg.upload.js"></script>
    <script src="~/lib/prism.js"></script>
    <script src="~/dist/plugins/highlight/trumbowyg.highlight.min.js"></script>
    <script src="~/dist/plugins/colors/trumbowyg.colors.min.js"></script>
    <script src="~/dist/plugins/history/trumbowyg.history.min.js"></script>
    <script src="~/dist/plugins/pasteembed/trumbowyg.pasteembed.min.js"></script>
    <script src="~/dist/plugins/table/trumbowyg.table.min.js"></script>
    <script src="~/dist/plugins/template/trumbowyg.template.min.js"></script>
    
    @* <script src="//cdn.rawgit.com/Alex-D/Trumbowyg/v2.10.0/dist/plugins/upload/trumbowyg.upload.js"></script> *@
    
    <script>
        $("#edit").trumbowyg({
            lang: 'zh',
            btnsDef: {
                image: {
                    dropdown: ['insertImage', 'upload', 'base64'],
                    ico: 'insertImage'
                }
            },
            btns: [
                ['viewHTML'],
                ['historyUndo', 'historyRedo'],
                ['foreColor', 'backColor'],
                ['formatting'],
                ['strong', 'em', 'del'],
                ['superscript', 'subscript'],
                ['link'],
                ['image'],
                ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                ['unorderedList', 'orderedList'],
                ['horizontalRule'],
                ['removeformat'],
                ['highlight'],
                ['table'],
                ['template'],
                ['fullscreen']
            ],
            plugins: {
                templates: [
                    {
                        name: "Test",
                        html: "<p>I am a template !</p>"
                    }
                ],
                upload : {
                    serverPath : '/edit',
                    fileFieldName : 'image',
//                    headers : {
//                        'Authorization' : '',
//                    },
                    urlPropertyName: 'data.link'
                }
            },
            autogrow: true,
            autogrowOnEnter: true,
            imageWidthModalEdit: true
        });
    </script>
}

WebApplication1/Pages/Edit2.cshtml
@page
@model Edit2Model

@{
}

<link rel="stylesheet" href="~/css/editormd.css"/>
<link rel="stylesheet" href="~/css/editormd.preview.css"/>

https://pandao.github.io/editor.md/

<form method="post">
    <input class="btn btn-primary" type="submit" value="Submit"/>
    <hr/>
    <div id="test-editormd"></div>
</form>

<hr/>

<div id="md">
    <textarea id="append-test">
    @Html.Raw(Model.Md)
    </textarea>
</div>

@section Scripts
{
    <script src="editormd.js"></script>
    <script src="~/lib/marked.min.js"></script>
    <script src="~/lib/prettify.min.js"></script>
    <script>
        var testEditor, testEditormdView;

        $(function() {

            testEditor = editormd("test-editormd",
                {
                    width: "90%",
                    height: 740,
                    path: '../lib/',
                    theme: "dark",
                    previewTheme: "dark",
                    editorTheme: "pastel-on-dark",
                    markdown: '',
                    codeFold: true,
                    //syncScrolling : false,
                    saveHTMLToTextarea: true, // 保存 HTML 到 Textarea
                    searchReplace: true,
                    //watch : false,                // 关闭实时预览
                    htmlDecode: "style,script,iframe|on*", // 开启 HTML 标签解析，为了安全性，默认不开启    
                    //toolbar  : false,             //关闭工具栏
                    //previewCodeHighlight : false, // 关闭预览 HTML 的代码块高亮，默认开启
//                        emoji: true,
                    taskList: true,
                    tocm: true, // Using [TOCM]
                    //dialogLockScreen : false,   // 设置弹出层对话框不锁屏，全局通用，默认为true
                    //dialogShowMask : false,     // 设置弹出层对话框显示透明遮罩层，全局通用，默认为true
                    //dialogDraggable : false,    // 设置弹出层对话框不可拖动，全局通用，默认为true
                    //dialogMaskOpacity : 0.4,    // 设置透明遮罩层的透明度，全局通用，默认值为0.1
                    //dialogMaskBgColor : "#000", // 设置透明遮罩层的背景颜色，全局通用，默认为#fff
                    imageUpload: true,
                    imageFormats: ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                    imageUploadURL: "/edit2?handler=img",
                    onload: function() {
                        console.log('onload', this);
                        //this.fullscreen();
                        //this.unwatch();
                        //this.watch().fullscreen();

                        //this.setMarkdown("#PHP");
                        //this.width("100%");
                        //this.height(480);
                        //this.resize("100%", 640);
                    }
                });

            testEditormdView = editormd.markdownToHTML("md",
                {
                    htmlDecode: "style,script,iframe", // you can filter tags decode
//                    emoji: true,
                    taskList: true,
//                    tex: true, // 默认不解析
//                    flowChart: true, // 默认不解析
//                    sequenceDiagram: true, // 默认不解析
                });


        });

    </script>
}

WebApplication1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload one or more files using this form:</p>
            <input type="file" name="files" multiple />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Upload" />
        </div>
    </div>
</form>

<br/>

@if (Model.ImgUrl.Count > 0)
{
    foreach (var url in Model.ImgUrl)
    {
       <img src="@url"/> 
    } 
}

<br/>
<br/>
<hr /> <hr />

<form method="post" asp-page-handler="Data">
    
    <button type="submit">Submit Data</button>
    
</form>

@if (Model.FObject != null)
{
    <h5>Key - @Model.Key</h5>
    <h5>Name - @Model.FObject.Name</h5>
    <h5>Url - @Model.FObject.Url</h5>
}

<br/>
<br/>
<hr /> <hr />

<form method="post" asp-page-handler="DataUpdate">
    
    <button type="submit">Update Data</button>
    
</form>

@if (Model.FObject != null)
{
    <h5>Key - @Model.Key</h5>
    <h5>Name - @Model.FObject.Name</h5>
    <h5>Url - @Model.FObject.Url</h5>
}